/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livraria.forms;

import javax.swing.table.DefaultTableModel;
import livraria.classes.autores;
import livraria.classes.editoras;
import livraria.classes.livros;
import livraria.DAO.autoresDAO;
import livraria.DAO.editorasDAO;
import livraria.DAO.livrosDAO;

/**
 *
 * @author igor.zampieri
 */
public class Livros_Form extends javax.swing.JFrame {

    /**
     * Creates new form Livros_Form
     */
    public Livros_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        carregaDados();
        
        editorasDAO edDao = new editorasDAO();
        autoresDAO auDao = new autoresDAO();
        
        for(editoras e : edDao.listar()) {
            jComboBox_Editoras.addItem(e);
        }
        
        for(autores a : auDao.listar()) {
            jComboBox_Autores.addItem(a);
        }
    }

    public void carregaDados() {
        
        DefaultTableModel tabela = (DefaultTableModel) jTable_Titulos.getModel();
        livrosDAO dao = new livrosDAO();
        tabela.setNumRows(0);
        
        for (livros l : dao.listar()) {
            tabela.addRow(new Object[]{
                l.getId_livro(),
                l.getEditora(),
                l.getAutor(),
                l.getTitulo(),
                l.getAno()
            });    
        }
    }
    
    public void pesquisaDados() {
        
        DefaultTableModel tabela = (DefaultTableModel) jTable_Titulos.getModel();
        livrosDAO dao = new livrosDAO();
        tabela.setNumRows(0);
        
        for (livros l: dao.pesquisar((jTextField_Pesquisar.getText()))) {
            tabela.addRow(new Object[]{
                l.getId_livro(),
                l.getEditora(),
                l.getAutor(),
                l.getTitulo(),
                l.getAno()
            });    
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Editoras = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Autores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Ano = new javax.swing.JTextField();
        jTextField_Codigo = new javax.swing.JTextField();
        jButton_Cadastrar = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Titulos = new javax.swing.JTable();
        jTextField_Pesquisar = new javax.swing.JTextField();
        jButton_Pesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Código:");

        jLabel3.setText("Editora:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Título:");

        jTextField_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TituloActionPerformed(evt);
            }
        });

        jLabel6.setText("Ano:");

        jTextField_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AnoActionPerformed(evt);
            }
        });

        jTextField_Codigo.setEnabled(false);

        jButton_Cadastrar.setText("Cadastrar");
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarActionPerformed(evt);
            }
        });

        jButton_Alterar.setText("Alterar");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jTable_Titulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Editora", "Autor", "Titulo", "Ano"
            }
        ));
        jTable_Titulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TitulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Titulos);

        jButton_Pesquisar.setText("Pesquisar");
        jButton_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PesquisarActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Editoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Autores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Alterar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Excluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_Editoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_Autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cadastrar)
                    .addComponent(jButton_Alterar)
                    .addComponent(jButton_Excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Pesquisar)
                    .addComponent(jTextField_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TituloActionPerformed

    private void jTextField_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AnoActionPerformed

    private void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarActionPerformed
        livros li = new livros();
        livrosDAO DAO = new livrosDAO();
        
        editoras editora = (editoras) jComboBox_Editoras.getSelectedItem();
        autores autor = (autores) jComboBox_Autores.getSelectedItem();
        
        li.setEditora(editora);
        li.setAutor(autor);
        li.setTitulo(jTextField_Titulo.getText());
        li.setAno(Integer.parseInt(jTextField_Ano.getText()));
        
        DAO.cadastrar(li);
        
        carregaDados();
    }//GEN-LAST:event_jButton_CadastrarActionPerformed

    private void jButton_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PesquisarActionPerformed
        pesquisaDados();
    }//GEN-LAST:event_jButton_PesquisarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        livros l = new livros();
        livrosDAO DAO = new livrosDAO();
        
        l.setId_livro(Integer.parseInt(jTextField_Codigo.getText()));
        DAO.excluir(l);
        
        carregaDados();
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTable_TitulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TitulosMouseClicked
        String comboEditoras = jTable_Titulos.getValueAt(jTable_Titulos.getSelectedRow(), 1).toString();
        for (int i = 0; i < jComboBox_Editoras.getItemCount(); i++) {
            if (jComboBox_Editoras.getItemAt(i).toString().equalsIgnoreCase(comboEditoras)) {
                jComboBox_Editoras.setSelectedIndex(i);
            }
        }
        
        String comboAutores = jTable_Titulos.getValueAt(jTable_Titulos.getSelectedRow(), 2).toString();
        for (int i = 0; i < jComboBox_Autores.getItemCount(); i++) {
            if (jComboBox_Autores.getItemAt(i).toString().equalsIgnoreCase(comboAutores)) {
                jComboBox_Autores.setSelectedIndex(i);
            }
        }
        
        jTextField_Codigo.setText(jTable_Titulos.getValueAt(jTable_Titulos.getSelectedRow(), 0).toString());
        jTextField_Titulo.setText(jTable_Titulos.getValueAt(jTable_Titulos.getSelectedRow(), 3).toString());
        jTextField_Ano.setText(jTable_Titulos.getValueAt(jTable_Titulos.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jTable_TitulosMouseClicked

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        
        livros l = new livros();
        livrosDAO dao = new livrosDAO();

        editoras editora = (editoras) jComboBox_Editoras.getSelectedItem();
        autores autor = (autores) jComboBox_Autores.getSelectedItem();

        l.setEditora(editora);
        l.setAutor(autor);
        l.setTitulo(jTextField_Titulo.getText());
        l.setAno(Integer.parseInt(jTextField_Ano.getText()));
        l.setId_livro(Integer.parseInt(jTextField_Codigo.getText()));
        
        dao.alterar(l);
        
        carregaDados();
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livros_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livros_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livros_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livros_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livros_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Pesquisar;
    private javax.swing.JComboBox<Object> jComboBox_Autores;
    private javax.swing.JComboBox<Object> jComboBox_Editoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Titulos;
    private javax.swing.JTextField jTextField_Ano;
    private javax.swing.JTextField jTextField_Codigo;
    private javax.swing.JTextField jTextField_Pesquisar;
    private javax.swing.JTextField jTextField_Titulo;
    // End of variables declaration//GEN-END:variables
}
