/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livraria.forms;

/**
 *
 * @author igos.zampieri
 */
public class Principal_Form extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Form
     */
    public Principal_Form() {
        
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_Titulos = new javax.swing.JMenu();
        jMenuItem_Cadastro_Editores = new javax.swing.JMenuItem();
        jMenuItem_Cadastro_Autores = new javax.swing.JMenuItem();
        jMenuItem_CadastroTitulos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Titulos.setText("Cadastros");

        jMenuItem_Cadastro_Editores.setText("Editores");
        jMenuItem_Cadastro_Editores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cadastro_EditoresActionPerformed(evt);
            }
        });
        jMenu_Titulos.add(jMenuItem_Cadastro_Editores);

        jMenuItem_Cadastro_Autores.setText("Autores");
        jMenuItem_Cadastro_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cadastro_AutoresActionPerformed(evt);
            }
        });
        jMenu_Titulos.add(jMenuItem_Cadastro_Autores);

        jMenuItem_CadastroTitulos.setText("Títulos");
        jMenuItem_CadastroTitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastroTitulosActionPerformed(evt);
            }
        });
        jMenu_Titulos.add(jMenuItem_CadastroTitulos);

        jMenuBar2.add(jMenu_Titulos);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Cadastro_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cadastro_AutoresActionPerformed
        
        // show a new form (Autores_Form)
        Autores_Form form = new Autores_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        // close the current form (Principal_Form)
        //this.dispose();
    }//GEN-LAST:event_jMenuItem_Cadastro_AutoresActionPerformed

    private void jMenuItem_Cadastro_EditoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cadastro_EditoresActionPerformed
        // show a new form (Editoras_Form)
        Editoras_Form form = new Editoras_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        // close the current form (Principal_Form)
        //this.dispose();
    }//GEN-LAST:event_jMenuItem_Cadastro_EditoresActionPerformed

    private void jMenuItem_CadastroTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastroTitulosActionPerformed
        // show a new form (Editoras_Form)
        Livros_Form form = new Livros_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        // close the current form (Principal_Form)
        //this.dispose();
    }//GEN-LAST:event_jMenuItem_CadastroTitulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_CadastroTitulos;
    private javax.swing.JMenuItem jMenuItem_Cadastro_Autores;
    private javax.swing.JMenuItem jMenuItem_Cadastro_Editores;
    private javax.swing.JMenu jMenu_Titulos;
    // End of variables declaration//GEN-END:variables
}
